### ISSUE TITLE
Severity levels based on the CVSS score

### ISSUE THREAD

**Issue by drawski** [pigulla/nsp-reporter-checkstyle#2]
It would be nice if the reporter set `severity` field based on CVSS score in the same way as it's done on the [NSP page](https://nodesecurity.io/advisories). Currently the value is hardcoded to `error`.
![screen shot 2017-12-05 at 15 26 22](https://user-images.githubusercontent.com/3234828/33612120-e81c9ffe-d9d0-11e7-84f8-deb46c36af68.png)

The mapping could be:
* `info`: CVSS score between up to 3.9
* `warning`: CVSS score between 4.0 and 6.9
* `error`: CVSS score above 7.0

**Comment by pigulla** [comment]
Thanks for the contribution! Version 1.1.0 is out now.
